name: ci-workflow-test
on:
  pull_request:
    branchs:
      - develop
strategy:
  matrix:
    version-go: ["1.15", "1.16"]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.version-go }}
      - run: go test
      - run: go run math.go
